FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN pip install pytest pytest-asyncio pytest-cov

COPY . .

CMD ["pytest", "src/tests/", "-v", "--cov=src"] 