version: "3.8"

services:
  app:
    volumes:
      - ./app:/src
    build: .
    ports:
    - "${PORT}:8000"
    environment:
    - DEBUG=${DEBUG}
    - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    env_file:
    - .app.env
    depends_on:
      - database

  web-proxy:
    image: nginx:stable
    depends_on: 
    - app
    ports:
      - "443:443"
      - "80:80"
  
  database:
    image: postgres:15-alpine
    volumes:
      - 'postgres_volume:/var/lib/postgresql/data'
    env_file:
      - .Postgres.env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:alpine
    ports:
    - "15675:15672"
    - "5675:5672"
    restart: "on-failure"
    volumes:
      - 'rabbitmq_volume:/var/lib/rabbitmq'

volumes:
  postgres_volume:
  rabbitmq_volume: 